name: Example Workflow

on:
  push:
    branches: [ main ]
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  print_secret:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_target' && (github.event.label.name == 'safe-to-test' || github.event.label.name == 'ok-to-test'))
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        env:
          SECURITY_KEY: ${{ secrets.SECURITY_KEY }}
        run: |
          echo "event name: ${{ github.event_name }}"
          [ "$SECURITY_KEY" = "qweqweqwe" ] && echo "Secret key matches expected value." || echo "Secret key does not match expected value."
          python -c "import os; print('The secret key is:', os.getenv('SECURITY_KEY'), os.getenv('SECURITY_KEY') == "qweqweqwe", flush=True)"